language: java

jdk:
  - oraclejdk8

sudo: required

before_install:
  - chmod +x gradlew

script:
  - ./gradlew clean build -i --continue

after_success:
  - ./gradlew test jacocoTestReport coveralls
